dist: xenial
sudo: required

language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    sources:
      - sourceline: 'ppa:wpilib/toolchain'
    packages:
      - frc-toolchain

install:
  - rustup target add arm-unknown-linux-gnueabi
  - rustup component add clippy-preview
  - wget http://devsite.ctr-electronics.com/maven/release/com/ctre/phoenix/cci/5.8.1/cci-5.8.1-linuxathena.zip -O cci-linuxathena.zip
  - mkdir -p ctre-sys/lib/athena
  - unzip -j cci-linuxathena.zip linux/athena/static/libCTRE_PhoenixCCI.a -d ctre-sys/lib/athena

before_script:
  - export CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABI=arm-frc-linux-gnueabi-gcc

script:
  - cargo clippy
  - cargo build --verbose --target arm-unknown-linux-gnueabi
