[package]
name = "ctre"
version = "0.5.1"
authors = ["David Vo <david@vovo.id.au>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/auscompgeek/ctre-rs"
description = "CTRE Phoenix for FRC library"

[dependencies]
ctre-sys = { path = "ctre-sys", version = "5.3.1" }
